<?php

declare(strict_types=1);

namespace App\Console\Commands;

use App\Domain\Auth\Services\PermissionMatrix;
use Illuminate\Console\Command;

/**
 * Emit the frontend permission metadata (`resources/spa/src/types/generated/
 * permissions.ts`) deterministically from the canonical permission matrix
 * (`docs/auth/permission-matrix.yaml`). This is the TypeScript leg of the §19.5
 * four-way parity contract (YAML ↔ PHP ↔ DB ↔ TS): the frontend metadata is
 * GENERATED, never hand-maintained, so it cannot drift from the security
 * contract. Only ACTIVE (runtime-enforced) keys are emitted — planned canonical
 * keys never become a frontend grant.
 *
 * `--check` regenerates in memory and fails (non-zero) if the committed file is
 * stale, for CI/pre-commit use.
 */
final class GeneratePermissionTypesCommand extends Command
{
    protected $signature = 'servana:permission-types {--check : Fail if the committed file is out of date instead of writing}';

    protected $description = 'Generate resources/spa/src/types/generated/permissions.ts from docs/auth/permission-matrix.yaml.';

    private const OUTPUT_PATH = 'resources/spa/src/types/generated/permissions.ts';

    public function handle(PermissionMatrix $matrix): int
    {
        $expected = $this->render($matrix);
        $path = base_path(self::OUTPUT_PATH);

        if ($this->option('check')) {
            $actual = is_file($path) ? (string) file_get_contents($path) : '';
            if ($actual !== $expected) {
                $this->error(self::OUTPUT_PATH.' is out of date. Run `php artisan servana:permission-types`.');

                return self::FAILURE;
            }

            $this->info(self::OUTPUT_PATH.' is up to date.');

            return self::SUCCESS;
        }

        file_put_contents($path, $expected);
        $this->info('Wrote '.self::OUTPUT_PATH.'.');

        return self::SUCCESS;
    }

    private function render(PermissionMatrix $matrix): string
    {
        $keys = $matrix->activeKeys();
        sort($keys);

        $lines = [];
        $lines[] = '// AUTO-GENERATED by `php artisan servana:permission-types`. Do not edit by hand.';
        $lines[] = '// Source of truth: docs/auth/permission-matrix.yaml (active runtime keys only).';
        $lines[] = '// Regenerate after any permission change; CI runs `--check` to prevent drift.';
        $lines[] = '';
        $lines[] = 'export interface PermissionMetadata {';
        $lines[] = '  readonly key: string;';
        $lines[] = "  readonly scope: 'platform' | 'merchant' | 'branch' | 'own';";
        $lines[] = '  readonly mfaRequired: boolean;';
        $lines[] = '  readonly stepUpRequired: boolean;';
        $lines[] = '}';
        $lines[] = '';
        $lines[] = 'export const PERMISSION_KEYS = [';
        foreach ($keys as $key) {
            $lines[] = "  '".$key."',";
        }
        $lines[] = '] as const;';
        $lines[] = '';
        $lines[] = 'export type PermissionKey = (typeof PERMISSION_KEYS)[number];';
        $lines[] = '';
        $lines[] = 'export const PERMISSION_METADATA: Record<PermissionKey, PermissionMetadata> = {';
        foreach ($keys as $key) {
            $row = $matrix->get($key);
            $lines[] = sprintf(
                "  '%s': { key: '%s', scope: '%s', mfaRequired: %s, stepUpRequired: %s },",
                $key,
                $key,
                (string) $row['scope'],
                $row['mfa_required'] ? 'true' : 'false',
                $row['step_up_required'] ? 'true' : 'false',
            );
        }
        $lines[] = '};';
        $lines[] = '';

        return implode("\n", $lines);
    }
}
