<?php

declare(strict_types=1);

namespace App\Domain\Auth\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

/**
 * Branded Magic Link sign-in email (Plan §9.1, §20 mail queue, brand voice).
 *
 * The raw token lives only on this notification instance and the rendered link;
 * it is never logged. The body carries no account data beyond the action itself.
 */
final class MagicLoginLinkNotification extends Notification implements ShouldQueue
{
    use Queueable;

    /**
     * @param  string  $verifyUrl  the ABSOLUTE verify URL for the bound account host, already
     *                             generated by AccountHostUrlGenerator from the registry. It is
     *                             passed in rather than built here so a request `Host` header can
     *                             never reach the emailed link (ADR-019; the classic
     *                             password-reset-poisoning shape).
     */
    public function __construct(
        private readonly string $rawToken,
        private readonly string $verifyUrl,
    ) {
        // Magic Links take mail-queue priority (Plan §20).
        $this->onQueue('mail');
    }

    /**
     * @return list<string>
     */
    public function via(object $notifiable): array
    {
        return ['mail'];
    }

    public function toMail(object $notifiable): MailMessage
    {
        return (new MailMessage)
            ->subject('Your Servana sign-in link')
            ->greeting('Sign in to Servana')
            ->line('Use the button below to sign in. For your security, this link works once and expires in 15 minutes.')
            ->action('Sign in to Servana', $this->signInUrl())
            ->line('If you did not request this, you can safely ignore this email — no one can sign in without the link.')
            ->salutation('— The Servana team');
    }

    /**
     * SPA verify route on the BOUND account host (Plan §9.1; ADR-019):
     * {scheme}://{account host}/auth/verify?token=<raw>.
     *
     * The link works on exactly one host. Presenting it anywhere else fails uniformly — that is
     * the whole anti-substitution control, and it is why the host is not a query parameter.
     */
    private function signInUrl(): string
    {
        return rtrim($this->verifyUrl, '/').'?token='.$this->rawToken;
    }
}
