<?php

declare(strict_types=1);

namespace App\Support\OpenApi;

use App\Http\Routing\RouteClass;
use App\Http\Routing\RouteClassification;
use Dedoc\Scramble\Generator as ScrambleGenerator;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Routing\Route;
use Illuminate\Routing\Router;

/**
 * OpenAPI contract for the Servana production API (Plan §23, §24; Phase 10
 * REM-ROUTE-001).
 *
 * The maintained **dedoc/scramble** generator is authoritative for OpenAPI schema
 * generation — it analyses the routes, Form Requests and API Resources and
 * produces the operations, request/response schemas, component schemas and
 * pagination/filter/sort parameters. This class is a thin Servana wrapper around
 * it that ONLY:
 *   - invokes the maintained generator;
 *   - restores full `/api/v1` paths under a single `/` server;
 *   - excludes test-only routes from the production inventory;
 *   - enforces operation IDs aligned with route names;
 *   - enforces production-route parity (drives the path set from the live route
 *     collection) and adds the `/health` probes Scramble does not cover;
 *   - augments the cross-cutting contract Scramble does not infer: the session
 *     security scheme, the §11.5 error envelope responses, and the financial
 *     `Idempotency-Key` header;
 *   - writes `docs/api/openapi.json` deterministically (sorted, byte-stable).
 */
final class OpenApiGenerator
{
    public function __construct(
        private readonly Router $router,
        private readonly ScrambleGenerator $scramble,
    ) {}

    /** @return array<string, mixed> */
    public function generate(): array
    {
        /** @var array<string, mixed> $document Authoritative document from dedoc/scramble. */
        $document = ($this->scramble)();

        $paths = [];

        foreach (($document['paths'] ?? []) as $relativePath => $methods) {
            if (! is_array($methods)) {
                continue;
            }

            foreach ($methods as $method => $operation) {
                if (! is_array($operation)) {
                    continue;
                }

                $route = $this->routeForOperation($operation);

                // Drop anything that is not a current production route (test-only
                // harness routes, or operations Scramble emitted for a route that
                // no longer exists). Production parity is the route collection.
                if ($route === null || ! $this->isProduction($route)) {
                    continue;
                }

                $fullPath = $this->fullPath($relativePath);
                $paths[$fullPath][strtolower((string) $method)] = $this->decorate($operation, $route, (string) $method);
            }
        }

        // Health probes live outside the api_path, so Scramble never sees them.
        foreach ($this->healthRoutes() as $route) {
            $paths['/'.ltrim($route->uri(), '/')]['get'] = $this->healthOperation($route);
        }

        ksort($paths);
        foreach ($paths as &$operations) {
            ksort($operations);
        }
        unset($operations);

        $components = is_array($document['components'] ?? null) ? $document['components'] : [];
        $components['schemas'] = $this->schemas($components['schemas'] ?? []);
        $components['securitySchemes'] = $this->securitySchemes($components['securitySchemes'] ?? []);
        ksort($components);

        return [
            'openapi' => is_string($document['openapi'] ?? null) ? $document['openapi'] : '3.1.0',
            'info' => [
                'title' => 'Servana by Citrus API',
                'version' => 'v1',
                'description' => 'Production API contract generated by dedoc/scramble (authoritative) via the Servana wrapper. Do not edit by hand — run `composer api:openapi`.',
            ],
            'servers' => [['url' => '/']],
            'paths' => $paths,
            'components' => $components,
        ];
    }

    /** Byte-stable pretty JSON (trailing newline) for the committed artifact. */
    public function toJson(): string
    {
        return json_encode(
            $this->generate(),
            JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR,
        )."\n";
    }

    /** @return list<Route> production API + health routes (test/framework excluded). */
    public function productionRoutes(): array
    {
        $routes = [];

        foreach ($this->router->getRoutes()->getRoutes() as $route) {
            if ($this->isProduction($route)) {
                $routes[] = $route;
            }
        }

        return $routes;
    }

    private function isProduction(Route $route): bool
    {
        $uri = $route->uri();
        $name = $route->getName() ?? '';

        $isApi = str_starts_with($uri, 'api/v1/') || $uri === 'health' || $uri === 'health/deep';

        if (! $isApi) {
            return false;
        }

        return ! str_starts_with($name, 'testing.') && ! str_contains($uri, 'api/v1/testing/');
    }

    /**
     * Resolve the route a Scramble operation belongs to via its (route-name) operationId.
     *
     * @param  array<string, mixed>  $operation
     */
    private function routeForOperation(array $operation): ?Route
    {
        $operationId = $operation['operationId'] ?? null;

        if (! is_string($operationId)) {
            return null;
        }

        return $this->router->getRoutes()->getByName($operationId);
    }

    /** Scramble strips the api_path prefix; restore the full `/api/v1/...` path. */
    private function fullPath(string $relativePath): string
    {
        $prefix = '/'.trim((string) config('scramble.api_path', 'api/v1'), '/');

        return rtrim($prefix, '/').'/'.ltrim($relativePath, '/');
    }

    /**
     * Augment a Scramble operation with the cross-cutting Servana contract:
     * confirmed operationId, security, standard error responses, idempotency.
     *
     * @param  array<string, mixed>  $operation
     * @return array<string, mixed>
     */
    private function decorate(array $operation, Route $route, string $method): array
    {
        $operation['operationId'] = $route->getName();

        $class = RouteClassification::of($route);

        $operation['security'] = $this->requiresAuth($route) ? [['sanctumSession' => []]] : [];

        if ($class === RouteClass::FinancialMutation) {
            $parameters = is_array($operation['parameters'] ?? null) ? $operation['parameters'] : [];
            $parameters[] = [
                'name' => 'Idempotency-Key',
                'in' => 'header',
                'required' => true,
                'schema' => ['type' => 'string', 'minLength' => 16, 'maxLength' => 255],
            ];
            $operation['parameters'] = $parameters;
        }

        $operation['responses'] = $this->mergeResponses(
            is_array($operation['responses'] ?? null) ? $operation['responses'] : [],
            $route,
            strtoupper($method),
            $class,
        );

        return $operation;
    }

    /**
     * Merge Scramble's success responses with the standard §11.5 error envelope
     * responses for this route's class. Scramble's success bodies are preserved.
     *
     * @param  array<int|string, mixed>  $responses
     * @return array<int|string, mixed>
     */
    private function mergeResponses(array $responses, Route $route, string $method, ?RouteClass $class): array
    {
        if ($this->requiresAuth($route)) {
            $responses['401'] ??= $this->errorRef('Unauthenticated');
            $responses['403'] ??= $this->errorRef('Permission denied');
        }

        if ($route->parameterNames() !== []) {
            $responses['404'] ??= $this->errorRef('Not found (foreign-tenant ids 404 without existence leak)');
        }

        if ($method !== 'GET' && ($class?->requiresValidation() ?? false)) {
            $responses['422'] ??= $this->errorRef('Validation failed');
        }

        if ($method === 'GET' && $this->hasQueryParameters($route)) {
            $responses['422'] ??= $this->errorRef('Invalid pagination/filter/sort');
        }

        if ($class === RouteClass::FinancialMutation) {
            $responses['409'] ??= $this->errorRef('Idempotency conflict / request in progress');
            $responses['423'] ??= $this->errorRef('Financial period locked');
        }

        $responses['429'] ??= $this->errorRef('Rate limited');

        ksort($responses);

        return $responses;
    }

    /** A GET route validates query input when its Form Request contributed params. */
    private function hasQueryParameters(Route $route): bool
    {
        $action = $route->getActionName();

        if (! str_contains($action, '@')) {
            return false;
        }

        [$class, $methodName] = explode('@', $action, 2);

        if (! class_exists($class) || ! method_exists($class, $methodName)) {
            return false;
        }

        foreach ((new \ReflectionMethod($class, $methodName))->getParameters() as $parameter) {
            $type = $parameter->getType();
            if ($type instanceof \ReflectionNamedType
                && ! $type->isBuiltin()
                && is_subclass_of($type->getName(), FormRequest::class)) {
                return true;
            }
        }

        return false;
    }

    /** @return array<string, mixed> */
    private function errorRef(string $description): array
    {
        return [
            'description' => $description,
            'content' => ['application/json' => ['schema' => ['$ref' => '#/components/schemas/ErrorEnvelope']]],
        ];
    }

    /** @return list<Route> */
    private function healthRoutes(): array
    {
        $routes = [];

        foreach ($this->router->getRoutes()->getRoutes() as $route) {
            if (in_array($route->uri(), ['health', 'health/deep'], true)) {
                $routes[] = $route;
            }
        }

        return $routes;
    }

    /** @return array<string, mixed> */
    private function healthOperation(Route $route): array
    {
        return [
            'operationId' => $route->getName(),
            'tags' => ['health'],
            'summary' => $route->getName(),
            'security' => [],
            'responses' => [
                '200' => [
                    'description' => $route->uri() === 'health' ? 'Liveness OK' : 'Readiness OK',
                    'content' => ['application/json' => ['schema' => ['type' => 'object']]],
                ],
                '503' => $route->uri() === 'health/deep'
                    ? ['description' => 'A required dependency is unhealthy', 'content' => ['application/json' => ['schema' => ['type' => 'object']]]]
                    : ['description' => 'Service unavailable', 'content' => ['application/json' => ['schema' => ['type' => 'object']]]],
            ],
        ];
    }

    private function requiresAuth(Route $route): bool
    {
        foreach ($this->router->gatherRouteMiddleware($route) as $middleware) {
            if (is_string($middleware) && str_contains($middleware, 'Illuminate\\Auth\\Middleware\\Authenticate')) {
                return true;
            }
        }

        return false;
    }

    /**
     * Keep Scramble's inferred component schemas (resources, Form Requests) and add
     * the standard error envelope. Sorted for determinism.
     *
     * @param  array<string, mixed>  $schemas
     * @return array<string, mixed>
     */
    private function schemas(array $schemas): array
    {
        $schemas['ErrorEnvelope'] = [
            'type' => 'object',
            'description' => 'Standard API error envelope (Plan §11.5).',
            'properties' => [
                'error' => [
                    'type' => 'object',
                    'properties' => [
                        'code' => ['type' => 'string'],
                        'message' => ['type' => 'string'],
                        'fields' => ['type' => 'object'],
                        'meta' => ['type' => 'object'],
                    ],
                    'required' => ['code', 'message'],
                ],
            ],
            'required' => ['error'],
        ];

        ksort($schemas);

        return $schemas;
    }

    /**
     * @param  array<string, mixed>  $schemes
     * @return array<string, mixed>
     */
    private function securitySchemes(array $schemes): array
    {
        $schemes['sanctumSession'] = [
            'type' => 'apiKey',
            'in' => 'cookie',
            'name' => 'servana_session',
            'description' => 'Laravel Sanctum first-party stateful session cookie + X-XSRF-TOKEN.',
        ];

        ksort($schemes);

        return $schemes;
    }
}
