<?php

declare(strict_types=1);

uses()->group('docs', 'ui01', 'contracts');

/*
 |==============================================================================
 | Phase UI-01 — as-built audit contract enforcement.
 |
 | UI-01 produces evidence, not fixes. Its value therefore rests entirely on the evidence being
 | complete, well-formed, deterministic and honest. This guard enforces exactly that, and nothing
 | about product quality: it never asserts a page renders, a defect is fixed, or a count improved.
 |
 | It is OFFLINE and deterministic. It reads the committed audit artifacts, the committed evidence
 | capture and the filesystem. It does not start a browser, a container or a build. The artifacts
 | it reads are regenerated by `node scripts/audit-ui-as-built.mjs`, whose `--check` mode proves a
 | second pass produces no diff.
 |
 | The one property it enforces about the FINDINGS is the phase boundary: every product defect must
 | remain open and must name a future owner phase. A UI-01 pull request that closed a product
 | defect would have exceeded its own mandate, and this test fails on it.
 */

const UI01_AUDIT_DIR = 'docs/frontend/audits/ui-01';
const UI01_PROOF_DIR = 'docs/proof/ui-01';
const UI01_REGISTER = UI01_AUDIT_DIR.'/defect-register.csv';

/** The six machine-readable artifacts the phase is required to produce. */
const UI01_ARTIFACTS = [
    'audit-manifest.json',
    'baseline-screenshot-manifest.json',
    'navigation-role-audit.json',
    'route-component-page-audit.json',
    'served-build-provenance.json',
    'theme-asset-legal-audit.json',
];

/** The eight canonical accounts and their binding authenticated page counts (UI/UX plan §0). */
const UI01_ACCOUNTS = [
    'super_administrator' => 22,
    'merchant_administrator' => 23,
    'merchant_branch' => 18,
    'merchant_human_resource' => 19,
    'merchant_finance' => 24,
    'merchant_front_office' => 19,
    'merchant_personnel' => 20,
    'merchant_audit' => 15,
];

/** The exactly-one-of classification vocabulary for an implementation claim (README §4). */
const UI01_CLASSIFICATIONS = ['true', 'false', 'unreachable', 'stale', 'not_claimed'];

/** The severity vocabulary (README §5). */
const UI01_SEVERITIES = ['critical', 'high', 'medium', 'low', 'observation'];

/** Every phase a defect may be assigned to. A defect owned by "UI-01" would be a phase violation. */
const UI01_OWNER_PHASES = [
    'UI-02', 'UI-03', 'UI-04', 'UI-05', 'UI-06', 'UI-07', 'UI-08', 'UI-09', 'UI-10',
    'UI-11', 'UI-12', 'UI-13', 'UI-14', 'UI-15', 'UI-16', 'UI-17',
    'Phase 25', 'external_gate', 'product_owner_decision',
];

/** @return array<string, mixed> */
function ui01Artifact(string $name): array
{
    $path = base_path(UI01_AUDIT_DIR."/{$name}");

    expect(file_exists($path))->toBeTrue(
        "{$name} is missing. Run: node scripts/audit-ui-as-built.mjs",
    );

    /** @var array<string, mixed> $decoded */
    $decoded = json_decode((string) file_get_contents($path), true, flags: JSON_THROW_ON_ERROR);

    return $decoded;
}

/**
 * Parse the defect register as strict RFC 4180. A hand-authored CSV whose prose contains commas
 * is exactly the sort of file that silently loses a column, so the parse is explicit rather than
 * delegated to str_getcsv line by line.
 *
 * @return list<array<string, string>>
 */
function ui01Register(): array
{
    $path = base_path(UI01_REGISTER);

    expect(file_exists($path))->toBeTrue('The UI-01 defect register is missing.');

    $handle = fopen($path, 'r');
    expect($handle)->not->toBeFalse();

    $header = fgetcsv($handle, escape: '');
    expect($header)->toBeArray();

    $rows = [];
    while (($row = fgetcsv($handle, escape: '')) !== false) {
        if ($row === [null]) {
            continue;
        }

        expect(count($row))->toBe(
            count($header),
            "Defect register row '{$row[0]}' has ".count($row).' fields, expected '.count($header).'.',
        );

        /** @var array<string, string> $assoc */
        $assoc = array_combine($header, $row);
        $rows[] = $assoc;
    }

    fclose($handle);

    return $rows;
}

// ---------------------------------------------------------------------------------------------
// 1. The artifacts exist, are well-formed and are self-describing
// ---------------------------------------------------------------------------------------------

it('produces every required audit artifact', function (): void {
    foreach (UI01_ARTIFACTS as $name) {
        expect(file_exists(base_path(UI01_AUDIT_DIR."/{$name}")))->toBeTrue("{$name} is missing.");
    }

    expect(file_exists(base_path(UI01_AUDIT_DIR.'/README.md')))->toBeTrue('The audit methodology README is missing.');
    expect(file_exists(base_path(UI01_REGISTER)))->toBeTrue('The defect register is missing.');
    expect(file_exists(base_path('docs/proof/ui-01.md')))->toBeTrue('The UI-01 phase proof is missing.');
    expect(is_dir(base_path(UI01_PROOF_DIR.'/screenshots')))->toBeTrue('The baseline screenshot directory is missing.');
    expect(is_dir(base_path(UI01_PROOF_DIR.'/network')))->toBeTrue('The sanitized network evidence directory is missing.');
});

it('stamps every artifact with a schema version and the owning phase', function (): void {
    foreach (UI01_ARTIFACTS as $name) {
        $artifact = ui01Artifact($name);

        expect($artifact)->toHaveKey('schema');
        expect((string) $artifact['schema'])->toStartWith('ui-01.audit.v1');
        expect($artifact)->toHaveKey('phase');
        expect($artifact['phase'])->toBe('UI-01');
    }
});

it('hashes every artifact and evidence input in the manifest', function (): void {
    $manifest = ui01Artifact('audit-manifest.json');

    /** @var list<array{path: string, sha256: string}> $artifacts */
    $artifacts = $manifest['artifacts'];
    $hashed = array_column($artifacts, 'sha256', 'path');

    foreach (UI01_ARTIFACTS as $name) {
        if ($name === 'audit-manifest.json') {
            continue; // A manifest cannot contain its own hash.
        }

        $path = UI01_AUDIT_DIR."/{$name}";
        // `toHaveKey`'s second argument is an expected VALUE, not a message — assert presence first.
        expect(array_key_exists($path, $hashed))->toBeTrue("{$name} is not hashed in the audit manifest.");
        expect($hashed[$path])->toBe(
            hash_file('sha256', base_path($path)),
            "{$name} does not match its manifest hash. Run: node scripts/audit-ui-as-built.mjs",
        );
    }

    expect(array_key_exists(UI01_REGISTER, $hashed))->toBeTrue('The defect register is not hashed in the audit manifest.');
    expect($hashed[UI01_REGISTER])->toBe(hash_file('sha256', base_path(UI01_REGISTER)));

    // Every source the audit read is hashed too, so a later phase can prove which inputs produced
    // these conclusions rather than assuming the inputs never moved.
    /** @var list<array{path: string, present: bool, sha256: ?string}> $sources */
    $sources = $manifest['source_inputs'];
    expect($sources)->not->toBeEmpty();

    foreach ($sources as $source) {
        if ($source['present'] !== true) {
            continue;
        }

        // The recorded hash must be a real digest — that is what makes "which inputs produced
        // these conclusions" answerable later.
        expect($source['sha256'])->toMatch('/^[0-9a-f]{64}$/');

        if ($source['sha256'] === hash_file('sha256', base_path($source['path']))) {
            continue;
        }

        /*
         | The input has moved since the audit. That is EXPECTED for shared, living sources — the
         | screen inventory grows every time a phase registers a route — and demanding they stay
         | byte-frozen would either freeze the programme or force a later phase to rewrite UI-01's
         | evidence, which §7.2 forbids. What must never move is the audit's OWN evidence.
         */
        $isUi01Evidence = str_starts_with($source['path'], 'docs/frontend/audits/ui-01/')
            || str_starts_with($source['path'], 'docs/proof/ui-01/');

        expect($isUi01Evidence)->toBeFalse(
            "UI-01's own evidence changed after the audit was generated: {$source['path']}. "
                .'Historical audit evidence is immutable.',
        );
    }
});

// ---------------------------------------------------------------------------------------------
// 2. Served-build provenance is a complete chain, never an assumption
// ---------------------------------------------------------------------------------------------

it('records the commit, tree and Vite manifest that produced the audited build', function (): void {
    $provenance = ui01Artifact('served-build-provenance.json');

    expect($provenance['git'])->toBeArray('Git provenance was not collected. Run --capture.');
    expect($provenance['git'])->toHaveKeys(['branch', 'head', 'head_tree', 'origin_main']);
    expect($provenance['git']['head'])->toMatch('/^[0-9a-f]{40}$/');
    expect($provenance['git']['head_tree'])->toMatch('/^[0-9a-f]{40}$/');

    expect($provenance['vite']['manifest_present'])->toBeTrue('No Vite manifest was recorded.');
    expect($provenance['vite']['manifest_sha256'])->toMatch('/^[0-9a-f]{64}$/');
    expect($provenance['vite']['emitted_asset_count'])->toBeGreaterThan(0);
});

it('reconciles every asset URL the built shell references against what the origin served', function (): void {
    $provenance = ui01Artifact('served-build-provenance.json');

    /** @var list<array{referenced_url: string, served_status: ?int}> $resolution */
    $resolution = $provenance['index_html']['referenced_url_resolution'];

    expect($resolution)->not->toBeEmpty('The built shell referenced no assets, which cannot be right.');

    foreach ($resolution as $entry) {
        expect($entry)->toHaveKeys(['referenced_url', 'served_status', 'exists_under_public_spa', 'exists_under_public_root']);
        expect($entry['referenced_url'])->toStartWith('/');
    }
});

it('separates the preview harness origin from the served origin', function (): void {
    $provenance = ui01Artifact('served-build-provenance.json');

    expect($provenance['browser'])->toBeArray('No browser evidence was collected.');
    expect($provenance['browser'])->toHaveKey('base_url_kind');

    // The distinction is the whole point of the phase: an assertion proven on the preview harness
    // is a statement about frontend code, not about the deployed product.
    expect((string) $provenance['browser']['base_url_kind'])->toContain('preview');
    expect($provenance['served_origin'])->not->toBe('not_collected');
});

// ---------------------------------------------------------------------------------------------
// 3. Every page claim is classified, and the two registers stay separate
// ---------------------------------------------------------------------------------------------

it('classifies every implementation claim exactly once from the permitted vocabulary', function (): void {
    $audit = ui01Artifact('route-component-page-audit.json');

    /** @var list<array<string, mixed>> $claims */
    $claims = $audit['implementation_claims'];

    $inventory = json_decode(
        (string) file_get_contents(base_path('docs/frontend/screens/inventory.json')),
        true,
        flags: JSON_THROW_ON_ERROR,
    );

    /*
     | The UI-01 audit is a HISTORICAL SNAPSHOT: it classified every screen-inventory row that
     | existed on 2026-07-29, and §7.2 of the corrective programme forbids re-running that
     | classification. Asserting an exact count against the LIVE inventory therefore made a later
     | phase unable to register a new screen without either rewriting UI-01's evidence or being
     | blocked — which is the opposite of what this guard is for.
     |
     | The invariant that actually matters is unchanged and is asserted directly: every row that
     | existed AT AUDIT TIME is classified, and no claim refers to a screen that does not exist.
     | Rows added afterwards belong to the phase that added them and carry their own proof.
     */
    /*
     | REGISTERED REMOVALS. A screen may leave the inventory, but never silently: the UI-01
     | register is frozen, so a claim it carries that no longer resolves must be accounted for
     | here, by the phase that removed the screen, with the evidence for the removal.
     |
     | This is an explicit register, not an exemption. A removal nobody recorded still fails, and
     | the case below fails again the moment a registered key reappears in the inventory — which
     | forces the entry out rather than letting it rot.
     */
    $registeredRemovals = [
        // Phase UI-07, defect UI07-ROUTE-001. Each of these four routes rendered
        // `DashboardStub.vue` — a six-line component reading "Phase 4 stub — implementation in
        // later phases" — so four contract pages were exposed as live routes that implemented
        // nothing, which UI/UX plan §7.2 and §13.5 forbid. The routes and the dead components
        // were removed; the canonical navigation contract reserves each page's route identity
        // with `implementation_status: planned` and a named owner phase, so none of them can be
        // silently renamed or quietly forgotten.
        // `platform-dashboard` is DELIBERATELY ABSENT from this list. UI-07 removed its
        // placeholder route and named UI-08 as the owner; UI-08 Increment 9B delivered the real
        // page — a server-side aggregate read at `/dashboard` — so the screen is back in the
        // inventory legitimately and the resurrection guard below is what forced this entry out.
        // That is the register working exactly as designed: a removal is temporary custody, and
        // the entry expires when the owner phase delivers.
        'front-office-dashboard' => 'UI-07 / UI07-ROUTE-001 — owner UI-13; docs/frontend/audits/ui-07/defect-closure.json',
        'personnel-dashboard' => 'UI-07 / UI07-ROUTE-001 — owner UI-14; docs/frontend/audits/ui-07/defect-closure.json',
        'audit-dashboard' => 'UI-07 / UI07-ROUTE-001 — owner UI-15; docs/frontend/audits/ui-07/defect-closure.json',

        // Phase UI-08, Increment 7B. Each of these two screens was a CONSOLIDATED surface that
        // delivered several contract pages behind tabs — `platform-registration-monitoring`
        // delivered §5.4.10, §5.4.11 and §5.4.12, and `platform-promotions` delivered §5.4.6 and
        // §5.4.7 — which is the defect UI-08 exists to correct. Their route identities were
        // retired and each contract page now has its own canonical route, component and inventory
        // row, so nothing was lost: the pages were SPLIT OUT, not deleted. The legacy components
        // and their specs went with the routes because nothing referenced them any more.
        'platform-promotions' => 'UI-08 / Increment 7B — split into platform-billing-promotions and platform-billing-free-periods; docs/proof/ui-08.md',
        'platform-registration-monitoring' => 'UI-08 / Increment 7B — split into platform-merchant-registrations, platform-merchants and platform-merchant-detail; docs/proof/ui-08.md',
    ];

    $inventoryKeys = array_column($inventory['screens'], 'key');
    $claimKeys = array_column($claims, 'claim_key');

    expect(array_values(array_diff($claimKeys, $inventoryKeys, array_keys($registeredRemovals))))->toBe(
        [],
        'The audit classifies a screen that is no longer in the inventory — the register may not be rewritten, so this means a screen was REMOVED and its removal needs its own evidence.',
    );

    // A registered removal must still BE a removal. If the screen returns, this fails and the
    // entry must go.
    $resurrected = array_values(array_intersect(array_keys($registeredRemovals), $inventoryKeys));
    expect($resurrected)->toBe(
        [],
        'A screen registered as removed is back in the inventory — remove it from the registered-removal list.',
    );

    // Claims may exceed the live inventory only by the screens that were registered as removed
    // above; anything beyond that means the frozen audit was edited.
    expect(count($claims))->toBeLessThanOrEqual(
        count($inventory['screens']) + count($registeredRemovals),
        'There are more classified claims than screens plus registered removals, which is impossible unless the audit was edited.',
    );

    $keys = [];
    foreach ($claims as $claim) {
        expect(in_array($claim['classification'], UI01_CLASSIFICATIONS, true))->toBeTrue(
            "Claim {$claim['claim_key']} has classification {$claim['classification']}, which is not in the permitted vocabulary.",
        );
        expect((string) $claim['rationale'])->not->toBe('');
        expect(in_array($claim['claim_key'], $keys, true))->toBeFalse("Claim {$claim['claim_key']} is classified twice.");
        $keys[] = $claim['claim_key'];
    }

    // A row the inventory does not claim is `not_claimed` — never `false`. Reporting absence as a
    // failed claim would manufacture defects the repository never asserted.
    foreach ($claims as $claim) {
        if ($claim['claimed_status'] !== 'implemented') {
            expect($claim['classification'])->toBe(
                'not_claimed',
                "Claim {$claim['claim_key']} has inventory status {$claim['claimed_status']} and must be not_claimed.",
            );
        }
    }
});

it('reconciles all 160 required pages without conflating them with implementation claims', function (): void {
    $audit = ui01Artifact('route-component-page-audit.json');

    /** @var list<array<string, mixed>> $required */
    $required = $audit['required_pages'];

    expect($required)->toHaveCount(160, 'The binding contract is 160 required pages.');

    foreach (UI01_ACCOUNTS as $account => $count) {
        $rows = array_filter($required, static fn (array $row): bool => $row['account_key'] === $account);

        expect($rows)->toHaveCount($count, "{$account} must contribute exactly {$count} required pages.");
    }

    foreach ($required as $row) {
        expect(['claimed_by_route', 'not_claimed'])->toContain($row['required_status']);
    }

    // The two registers describe different things and are never summed.
    expect($audit['semantics'])->toHaveKey('counts_are_not_interchangeable');
    expect($audit['totals']['implementation_claims_inspected'])->not->toBe($audit['totals']['required_pages']);
});

it('records navigation and role resolution for all eight accounts', function (): void {
    $navigation = ui01Artifact('navigation-role-audit.json');

    /** @var list<array<string, mixed>> $accounts */
    $accounts = $navigation['per_account'];

    expect(array_column($accounts, 'account_key'))->toBe(array_keys(UI01_ACCOUNTS));

    foreach ($accounts as $account) {
        expect($account)->toHaveKeys([
            'required_host',
            'required_nav_placement',
            'source_nav_placement',
            'nav_placement_matches_contract',
            'layout_component',
            'browser_observed',
        ]);

        // Only the Super Administrator uses header navigation (ADR-018). The audit records what
        // the source says; this asserts the audit asked the right question of every account.
        $expected = $account['account_key'] === 'super_administrator' ? 'header' : 'sidebar';
        expect($account['required_nav_placement'])->toBe($expected);
    }
});

// ---------------------------------------------------------------------------------------------
// 4. The screenshot baseline is complete, provenanced and honest about what it could not capture
// ---------------------------------------------------------------------------------------------

it('provenances every baseline screenshot and represents every surface it could not capture', function (): void {
    $manifest = ui01Artifact('baseline-screenshot-manifest.json');

    /** @var list<array<string, mixed>> $shots */
    $shots = $manifest['screenshots'];

    expect($shots)->not->toBeEmpty('No baseline screenshots were recorded.');

    foreach ($shots as $shot) {
        expect(['captured', 'unreachable', 'not_configured', 'failed'])->toContain($shot['result']);
        expect($shot['source_commit'])->toMatch('/^[0-9a-f]{40}$/');
        expect($shot['viewport_width'])->toBeGreaterThan(0);

        if ($shot['result'] !== 'captured') {
            // An absent surface is evidence. It must be represented, and it must not claim a file.
            expect($shot['path'])->toBeNull("A non-captured screenshot for {$shot['route']} must not name a file.");

            continue;
        }

        expect($shot['path'])->toBeString();
        expect(file_exists(base_path((string) $shot['path'])))->toBeTrue("Screenshot {$shot['path']} is missing.");
        expect($shot['sha256'])->toBe(
            hash_file('sha256', base_path((string) $shot['path'])),
            "Screenshot {$shot['path']} does not match its recorded hash.",
        );
    }
});

it('states that the baseline is an as-built comparison point and not an approved baseline', function (): void {
    $manifest = ui01Artifact('baseline-screenshot-manifest.json');

    expect((string) $manifest['purpose'])->toContain('UI-16');
    expect((string) $manifest['purpose'])->toContain('NOT approved');
});

// ---------------------------------------------------------------------------------------------
// 5. The defect register is complete, and the phase boundary held
// ---------------------------------------------------------------------------------------------

it('records a complete, well-formed defect register', function (): void {
    $rows = ui01Register();

    expect($rows)->not->toBeEmpty('The defect register is empty.');

    $ids = [];
    foreach ($rows as $row) {
        expect($row['id'])->toMatch('/^UI01-[A-Z0-9]+-\d{3}$/');
        expect(in_array($row['id'], $ids, true))->toBeFalse("Defect id {$row['id']} appears twice.");
        $ids[] = $row['id'];

        expect(in_array($row['severity'], UI01_SEVERITIES, true))->toBeTrue(
            "Defect {$row['id']} has severity {$row['severity']}, which is not in the permitted vocabulary.",
        );
        expect(in_array($row['root_cause_status'], ['proven', 'unproven'], true))->toBeTrue(
            "Defect {$row['id']} has root_cause_status {$row['root_cause_status']}.",
        );

        foreach (['observed_problem', 'governing_requirement', 'expected_behavior', 'actual_behavior', 'evidence_paths', 'affected_accounts', 'future_acceptance_test'] as $field) {
            expect($row[$field])->not->toBe('', "Defect {$row['id']} has an empty {$field}.");
        }
    }
});

it('cites at least one evidence path that exists for every defect', function (): void {
    foreach (ui01Register() as $row) {
        $paths = array_filter(array_map(
            // Evidence entries carry a parenthesised pointer to the field inside the file.
            static fn (string $entry): string => trim(preg_replace('/\s*\(.*$/', '', trim($entry)) ?? ''),
            explode(';', $row['evidence_paths']),
        ));

        expect($paths)->not->toBeEmpty("Defect {$row['id']} cites no evidence path.");

        $found = false;
        foreach ($paths as $path) {
            if (file_exists(base_path($path)) || is_dir(base_path($path))) {
                $found = true;

                break;
            }
        }

        expect($found)->toBeTrue("Defect {$row['id']} cites no evidence path that exists: {$row['evidence_paths']}");
    }
});

it('leaves every product defect open and assigned to a future phase', function (): void {
    foreach (ui01Register() as $row) {
        // UI-01 resolves the absence of trustworthy evidence, never the defects it discovers. A
        // closed row here would mean the audit branch also carried a product fix.
        expect($row['status'])->toBe('open', "Defect {$row['id']} is not open. UI-01 must not fix product defects.");

        expect(in_array($row['future_owner_phase'], UI01_OWNER_PHASES, true))->toBeTrue(
            "Defect {$row['id']} names owner phase {$row['future_owner_phase']}, which is not a valid future owner.",
        );

        expect($row['entry_condition'])->not->toBe('', "Defect {$row['id']} has no entry condition.");
    }
});

// ---------------------------------------------------------------------------------------------
// 6. The evidence carries no secrets
// ---------------------------------------------------------------------------------------------

it('commits no raw HAR and no credential material in the network evidence', function (): void {
    $files = glob(base_path(UI01_PROOF_DIR.'/network/*')) ?: [];

    expect($files)->not->toBeEmpty('No network evidence was committed.');

    foreach ($files as $file) {
        expect(pathinfo($file, PATHINFO_EXTENSION))->toBe('json', 'Only sanitized JSON evidence may be committed.');
        expect(basename($file))->not->toContain('.har');

        $contents = (string) file_get_contents($file);

        foreach (['set-cookie', 'authorization:', 'bearer ey', 'x-csrf-token', 'xsrf-token'] as $marker) {
            expect(str_contains(strtolower($contents), $marker))->toBeFalse(
                basename($file)." contains '{$marker}'. Network evidence must be sanitized before it is committed.",
            );
        }
    }
});
