<?php

declare(strict_types=1);

uses()->group('docs', 'ui05', 'contracts', 'content', 'generation');

/*
 |==============================================================================
 | Phase UI-05 — generated-artifact shape and provenance.
 |
 | The generated modules are committed source. Committed generated source is only trustworthy if
 | three things hold: it is never hand-edited, it declares where it came from, and the committed
 | bytes are exactly what the generator produces from the committed inputs.
 |
 | The third is proven by `Ui05GeneratedArtifactStalenessTest`, which runs the generator in check
 | mode. This file proves the first two, plus the structural contract every module must satisfy.
 */

it('marks every generated content artifact as generated and names its regenerator', function (): void {
    $files = [];
    $directory = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator(base_path('resources/spa/src/content/generated'), FilesystemIterator::SKIP_DOTS),
    );
    /** @var SplFileInfo $file */
    foreach ($directory as $file) {
        if ($file->isFile()) {
            $files[] = str_replace([base_path().DIRECTORY_SEPARATOR, '\\'], ['', '/'], $file->getPathname());
        }
    }
    sort($files);

    // 40 documents + types + manifest + index + the landing-image module.
    expect($files)->toHaveCount(44);

    foreach ($files as $relative) {
        $header = (string) file_get_contents(base_path($relative), false, null, 0, 1024);

        expect($header)->toContain('GENERATED FILE — do not edit by hand.');
        expect($header)->toMatch('#Generated by: node scripts/generate-(role-content|landing-images)\.mjs#');
        expect($relative)->toEndWith('.generated.ts');
    }
});

it('declares the source path, hash and byte length inside every content module', function (): void {
    $manifest = ui05Audit('content-source-manifest');

    /** @var list<array<string, mixed>> $entries */
    $entries = $manifest['entries'];
    foreach ($entries as $entry) {
        $module = (string) file_get_contents(base_path((string) $entry['generated_module']));

        expect($module)->toContain('sourcePath: "'.$entry['source_path'].'"');
        expect($module)->toContain('sourceSha256: "'.$entry['source_sha256'].'"');
        expect($module)->toContain('sourceBytes: '.$entry['source_bytes'].',');
        expect($module)->toContain('parserVersion: "'.$entry['parser_version'].'"');

        // The manifest's record of the generated bytes must match the file on disk.
        expect(hash('sha256', $module))->toBe(
            $entry['generated_sha256'],
            "{$entry['generated_module']} does not match its recorded hash.",
        );
    }
});

it('emits a typed contract with no escape hatches', function (): void {
    $types = (string) file_get_contents(base_path('resources/spa/src/content/generated/contentTypes.generated.ts'));

    foreach ([
        'ContentAccountKey', 'ContentCategory', 'LandingRegion', 'ContentSourceMeta',
        'GeneratedLegalDocument', 'GeneratedFaqItem', 'GeneratedFaqDocument',
        'GeneratedLandingSection', 'GeneratedLandingDocument', 'ContentManifest',
    ] as $symbol) {
        expect($types)->toContain($symbol);
    }

    foreach ([
        'resources/spa/src/content/generated/contentTypes.generated.ts',
        'resources/spa/src/content/generated/contentManifest.generated.ts',
        'resources/spa/src/content/generated/index.generated.ts',
        'resources/spa/src/content/generated/landingImages.generated.ts',
    ] as $relative) {
        $module = (string) file_get_contents(base_path($relative));

        expect(preg_match('/\bany\b(?!\w)/', preg_replace('#//.*$#m', '', $module) ?? ''))
            ->toBe(0, "{$relative} uses `any`.");
        expect(preg_match('/@ts-(ignore|expect-error|nocheck)/', $module))
            ->toBe(0, "{$relative} suppresses type checking.");
        expect(preg_match('/!\./', $module))->toBe(0, "{$relative} uses a non-null assertion.");
    }
});

it('keeps the runtime free of build-time repository discovery', function (): void {
    foreach ([
        'resources/spa/src/content/legalContent.ts',
        'resources/spa/src/content/roleDocuments.ts',
        'resources/spa/src/content/roleContent.ts',
    ] as $relative) {
        $module = (string) file_get_contents(base_path($relative));
        $code = preg_replace('#(/\*\*.*?\*/)|(//.*$)#ms', '', $module) ?? '';

        expect($code)->not->toContain('import.meta.glob');
        expect($code)->not->toContain('?raw');
        expect($code)->not->toContain('@docs/');
        expect($code)->not->toContain('../../../../docs');
    }
});

it('records the landing-region contract for all eight accounts', function (): void {
    foreach (UI05_ACCOUNTS as $account) {
        $module = (string) file_get_contents(base_path("resources/spa/src/content/generated/{$account}/landing.generated.ts"));

        expect(substr_count($module, 'region: "'))->toBe(16, "{$account} does not record all sixteen plan regions.");
        expect(substr_count($module, 'presence: "'))->toBe(16);
        expect(substr_count($module, 'contentRestriction: "'))->toBe(16);
    }
});

it('does not duplicate a document\'s bytes inside its own compiled structure', function (): void {
    // Legal modules carry the full text once, verbatim — that is their contract. FAQ and landing
    // modules carry the compiled pieces instead: shipping a second copy of the same bytes beside
    // them would double each chunk for no consumer.
    foreach (UI05_ACCOUNTS as $account) {
        foreach (['faq', 'landing'] as $module) {
            $text = (string) file_get_contents(base_path("resources/spa/src/content/generated/{$account}/{$module}.generated.ts"));
            expect(preg_match('/^const markdown = /m', $text))->toBe(0, "{$account}/{$module} duplicates the source text.");
        }
        foreach (['data-policy', 'privacy-policy', 'terms-of-service'] as $module) {
            $text = (string) file_get_contents(base_path("resources/spa/src/content/generated/{$account}/{$module}.generated.ts"));
            expect(preg_match('/^const markdown = /m', $text))->toBe(1, "{$account}/{$module} lost its verbatim text.");
        }
    }
});
