<?php

declare(strict_types=1);

namespace App\Domain\Receipts\Actions;

use App\Domain\Audit\Contracts\AuditRecorder;
use App\Domain\Audit\Enums\AuditEvent;
use App\Domain\Receipts\Jobs\GenerateReceiptPdf;
use App\Domain\Receipts\Models\Receipt;
use App\Domain\Receipts\Services\ReceiptNumberAllocator;
use App\Models\User;
use Illuminate\Support\Facades\DB;

/**
 * Reissue a receipt (Plan §13.16, §43; Gate J; Phase 18B). Creates a NEW immutable
 * receipt row that references the ORIGINAL (never a reissue-of-a-reissue: the linkage
 * always points at the original), with a NEW gap-free per-merchant number. The original
 * row is never mutated. A fresh private `receipt_pdf` is generated by the outbox job
 * after commit. `receipt.reissue` is `PL n/a` (never period-locked). Money is integer
 * minor units; the components snapshot is copied verbatim (safe method+amount only).
 */
final class ReissueReceipt
{
    public function __construct(
        private readonly ReceiptNumberAllocator $numbers,
        private readonly AuditRecorder $audit,
    ) {}

    public function handle(Receipt $receipt, User $actor, string $reason): Receipt
    {
        $new = DB::transaction(function () use ($receipt, $actor, $reason): Receipt {
            /** @var Receipt $original */
            $original = Receipt::query()
                ->whereKey($receipt->reissue_of_receipt_id ?? $receipt->id)
                ->lockForUpdate()
                ->firstOrFail();

            $number = $this->numbers->allocate($original->merchant_id);

            $reissue = Receipt::create([
                'merchant_id' => $original->merchant_id,
                'branch_id' => $original->branch_id,
                'invoice_id' => $original->invoice_id,
                'payment_validation_event_id' => $original->payment_validation_event_id,
                'receipt_number' => $number,
                'amount_minor' => $original->amount_minor,
                'currency' => $original->currency,
                'components' => $original->components,
                'reissue_of_receipt_id' => $original->id,
                'reason' => $reason,
                'file_id' => null,
                'file_generation_status' => 'pending',
                'issued_by' => $actor->id,
            ]);

            $this->audit->record(AuditEvent::ReceiptReissued, $actor, $reissue->merchant_id, $reissue->branch_id, $reissue, [
                'receipt_id' => $reissue->ulid,
                'receipt_number' => $reissue->receipt_number,
                'reissue_of_receipt_id' => $original->ulid,
                'original_receipt_number' => $original->receipt_number,
                'amount_minor' => $reissue->amount_minor,
                'currency' => $reissue->currency,
                'reason' => $reason,
            ]);

            GenerateReceiptPdf::dispatch($reissue->id, $reissue->merchant_id, $reissue->branch_id)
                ->afterCommit()
                ->onQueue((string) config('files.queue', 'default'));

            return $reissue;
        });

        return $new;
    }
}
