/**
 * The Servana shared-component registry (Phase UI-04; UI/UX plan §10).
 *
 * A machine-readable contract for every shared component: where it lives, what it is for, which
 * states it supports, and where its test lives. `ComponentContractTest` reads this and fails the
 * build when a declared component is missing, untested, absent from the fixture, or a placeholder.
 *
 * The `states` field is honest rather than aspirational: a component that genuinely has no
 * loading state declares `not_applicable` instead of implementing fake behaviour. A registry that
 * claimed every component did everything would prove nothing.
 */

export type SvComponentCategory =
  | 'primitive'
  | 'feedback'
  | 'overlay'
  | 'form'
  | 'data'
  | 'shell'
  | 'content';

/** A state a component may support. `not_applicable` is a deliberate, documented answer. */
export type SvComponentState =
  | 'loading'
  | 'disabled'
  | 'readonly'
  | 'error'
  | 'empty'
  | 'selected'
  | 'expanded';

export interface SvComponentContract {
  name: string;
  category: SvComponentCategory;
  /** Repository-relative source path. */
  source: string;
  /** Repository-relative spec that exercises it. */
  test: string;
  /** What it is for, in one sentence. */
  purpose: string;
  /** States it genuinely implements. Absent states are `not_applicable` by omission. */
  states: SvComponentState[];
  /** Keyboard contract, or `not_applicable` for a non-interactive component. */
  keyboard: string;
  /** Responsive behaviour, or `not_applicable` when it does not change across breakpoints. */
  responsive: string;
  /** Both themes are mandatory; this records HOW, not whether. */
  theme: string;
}

const UI = 'resources/spa/src/components/ui/';
const PRIMITIVES = `${UI}SvPrimitives.spec.ts`;
const FEEDBACK = `${UI}SvFeedback.spec.ts`;
const OVERLAYS = `${UI}SvOverlays.spec.ts`;
const FORMS = `${UI}SvForms.spec.ts`;
const DATA = `${UI}SvData.spec.ts`;
const SHELL = `${UI}SvShellControls.spec.ts`;
const CONTENT = `${UI}SvContent.spec.ts`;

export const COMPONENT_REGISTRY: readonly SvComponentContract[] = Object.freeze([
  // ------------------------------------------------------------------ primitives
  {
    name: 'SvButton',
    category: 'primitive',
    source: `${UI}SvButton.vue`,
    test: PRIMITIVES,
    purpose: 'The canonical action control. Performs an action; never navigates.',
    states: ['loading', 'disabled'],
    keyboard: 'Native button: Enter and Space activate. Disabled and loading are non-interactive.',
    responsive: 'Optional block variant for the mobile primary action; 44px target at every size.',
    theme: 'Four token-backed variants; visible focus in both themes via .sv-focus-ring.',
  },
  {
    name: 'SvIconButton',
    category: 'primitive',
    source: `${UI}SvIconButton.vue`,
    test: PRIMITIVES,
    purpose: 'An icon-only control whose accessible name is a required prop.',
    states: ['loading', 'disabled', 'expanded', 'selected'],
    keyboard: 'Native button. Reflects aria-expanded/aria-controls/aria-pressed when supplied.',
    responsive: 'not_applicable — fixed 44x44 minimum at every breakpoint.',
    theme: 'Three token-backed variants; visible focus in both themes.',
  },
  {
    name: 'SvLink',
    category: 'primitive',
    source: `${UI}SvLink.vue`,
    test: PRIMITIVES,
    purpose: 'Navigation. Internal RouterLink or external anchor with a safe new-tab contract.',
    states: ['disabled'],
    keyboard: 'Native anchor. A disabled link renders a span, so it leaves the tab order entirely.',
    responsive: 'not_applicable — inline element.',
    theme: 'Link and hover colours are semantic tokens in both themes.',
  },
  {
    name: 'SvLogo',
    category: 'primitive',
    source: `${UI}SvLogo.vue`,
    test: PRIMITIVES,
    purpose: 'The approved Logo.png wordmark at three sizes, with explicit dimensions.',
    states: [],
    keyboard: 'not_applicable — an image.',
    responsive: 'Three fixed sizes chosen by the caller; aspect ratio preserved.',
    theme: 'The approved bitmap is never recoloured or filtered in either theme.',
  },
  {
    name: 'SvPageHeader',
    category: 'primitive',
    source: `${UI}SvPageHeader.vue`,
    test: PRIMITIVES,
    purpose: 'The single page-title region. Owns the page h1.',
    states: [],
    keyboard: 'not_applicable — a layout region; its slotted controls carry their own contracts.',
    responsive: 'Actions stack full width on mobile and sit inline from tablet up.',
    theme: 'Heading and muted description use semantic tokens.',
  },
  {
    name: 'SvBreadcrumbs',
    category: 'primitive',
    source: `${UI}SvBreadcrumbs.vue`,
    test: PRIMITIVES,
    purpose: 'Ancestor navigation as a named nav landmark containing an ordered list.',
    states: [],
    keyboard: 'Native links; the current page is text with aria-current="page".',
    responsive: 'The middle of a long trail is hidden below tablet but stays in the DOM.',
    theme: 'Link and separator colours are semantic tokens.',
  },
  {
    name: 'SvCard',
    category: 'primitive',
    source: `${UI}SvCard.vue`,
    test: PRIMITIVES,
    purpose: 'A grouped content surface. Deliberately not clickable.',
    states: [],
    keyboard: 'not_applicable — a container; it never captures activation from its contents.',
    responsive: 'Four padding steps chosen by the caller.',
    theme: 'Raised surface and border are semantic tokens.',
  },
  {
    name: 'SvMetricCard',
    category: 'primitive',
    source: `${UI}SvMetricCard.vue`,
    test: PRIMITIVES,
    purpose: 'A headline figure with optional trend. Computes nothing.',
    states: ['loading'],
    keyboard: 'not_applicable — presentation only.',
    responsive: 'Fills its grid cell.',
    theme: 'Trend tones are semantic status tokens; direction is also stated in text.',
  },
  {
    name: 'SvStatusBadge',
    category: 'primitive',
    source: `${UI}SvStatusBadge.vue`,
    test: PRIMITIVES,
    purpose: 'A status indicator whose label is always rendered as text.',
    states: [],
    keyboard: 'not_applicable — presentation only.',
    responsive: 'Two sizes.',
    theme: 'Five token-backed tones, contrast-checked in both themes.',
  },
  {
    name: 'SvMoney',
    category: 'primitive',
    source: `${UI}SvMoney.vue`,
    test: PRIMITIVES,
    purpose: 'Integer-minor-unit money. Unavailable is never rendered as zero.',
    states: [],
    keyboard: 'not_applicable — presentation only.',
    responsive: 'Three sizes; tabular numerals so columns align.',
    theme: 'Muted unavailable state and signed negative use semantic tokens.',
  },
  {
    name: 'SvDateTime',
    category: 'primitive',
    source: `${UI}SvDateTime.vue`,
    test: PRIMITIVES,
    purpose: 'A timestamp or business date in Africa/Nairobi, never the browser timezone.',
    states: [],
    keyboard: 'not_applicable — presentation only.',
    responsive: 'not_applicable — inline element.',
    theme: 'Muted unavailable state uses a semantic token.',
  },

  // ------------------------------------------------------------------ feedback
  {
    name: 'SvAlert',
    category: 'feedback',
    source: `${UI}SvAlert.vue`,
    test: FEEDBACK,
    purpose: 'An inline message attached to the content it concerns.',
    states: ['error'],
    keyboard: 'The dismiss control is a named icon button.',
    responsive: 'Stacks its action row on narrow widths.',
    theme: 'Four severities, each a token triple, contrast-checked in both themes.',
  },
  {
    name: 'SvBanner',
    category: 'feedback',
    source: `${UI}SvBanner.vue`,
    test: FEEDBACK,
    purpose: 'A page- or account-level notice. A named region, not a live region.',
    states: ['error'],
    keyboard: 'The dismiss control names the banner it dismisses.',
    responsive: 'Wraps its action row on narrow widths.',
    theme: 'Three severities from semantic tokens.',
  },
  {
    name: 'SvToast',
    category: 'feedback',
    source: `${UI}SvToast.vue`,
    test: FEEDBACK,
    purpose: 'Transient, globally positioned confirmations from the notification store.',
    states: [],
    keyboard: 'Each toast carries a named dismiss control.',
    responsive: 'Anchored above the fixed footer at every breakpoint.',
    theme: 'Four token-backed types.',
  },
  {
    name: 'SvSkeleton',
    category: 'feedback',
    source: `${UI}SvSkeleton.vue`,
    test: FEEDBACK,
    purpose: 'A decorative loading placeholder that never looks like data.',
    states: ['loading'],
    keyboard: 'not_applicable — hidden from assistive technology.',
    responsive: 'Fills the box the real content will occupy.',
    theme: 'Subtle surface token; animation suppressed under reduced motion.',
  },
  {
    name: 'SvEmptyState',
    category: 'feedback',
    source: `${UI}SvEmptyState.vue`,
    test: FEEDBACK,
    purpose: 'There is genuinely nothing here yet.',
    states: ['empty'],
    keyboard: 'The optional action is a native button.',
    responsive: 'Centred column at every breakpoint.',
    theme: 'Warm surface and muted text tokens.',
  },
  {
    name: 'SvErrorState',
    category: 'feedback',
    source: `${UI}SvErrorState.vue`,
    test: FEEDBACK,
    purpose: 'The request failed. Retry is offered only when repeating is safe.',
    states: ['error'],
    keyboard: 'The retry control is a native button.',
    responsive: 'Centred column at every breakpoint.',
    theme: 'Error tokens, contrast-checked in both themes.',
  },
  {
    name: 'SvOfflineState',
    category: 'feedback',
    source: `${UI}SvOfflineState.vue`,
    test: FEEDBACK,
    purpose: 'The browser has no connection. A different remedy from a server error.',
    states: ['error'],
    keyboard: 'The retry control is a native button.',
    responsive: 'Centred column at every breakpoint.',
    theme: 'Muted surface tokens.',
  },
  {
    name: 'SvPermissionState',
    category: 'feedback',
    source: `${UI}SvPermissionState.vue`,
    test: FEEDBACK,
    purpose: 'You may not view this. Never names the resource or confirms it exists.',
    states: [],
    keyboard: 'not_applicable — no control; a correct refusal has no retry.',
    responsive: 'Centred column at every breakpoint.',
    theme: 'Neutral tokens — a refusal is not an error.',
  },
  {
    name: 'SvLockedState',
    category: 'feedback',
    source: `${UI}SvLockedState.vue`,
    test: FEEDBACK,
    purpose: 'This exists and you may see it, but a business rule has closed it to changes.',
    states: [],
    keyboard: 'Slotted actions carry their own contracts.',
    responsive: 'Centred column at every breakpoint.',
    theme: 'Warning tokens.',
  },

  // ------------------------------------------------------------------ overlays
  {
    name: 'SvDialog',
    category: 'overlay',
    source: `${UI}SvDialog.vue`,
    test: OVERLAYS,
    purpose: 'The canonical modal dialog, built on the one shared focus trap.',
    states: ['expanded'],
    keyboard: 'Focus enters on open and is trapped; Escape closes unless persistent; focus returns to the trigger.',
    responsive: 'Height-capped and internally scrolling, so it fits at 360px and at 200% zoom.',
    theme: 'Scrim and raised surface are semantic tokens.',
  },
  {
    name: 'SvConfirmDialog',
    category: 'overlay',
    source: `${UI}SvConfirmDialog.vue`,
    test: OVERLAYS,
    purpose: 'Confirm before an irreversible action. Focuses Cancel when destructive.',
    states: ['loading', 'error', 'expanded'],
    keyboard: 'Inherits SvDialog; initial focus is Cancel for a destructive action.',
    responsive: 'Inherits SvDialog.',
    theme: 'Destructive variant uses error tokens.',
  },
  {
    name: 'SvDrawer',
    category: 'overlay',
    source: `${UI}SvDrawer.vue`,
    test: OVERLAYS,
    purpose: 'An off-canvas panel sharing the one focus trap.',
    states: ['expanded'],
    keyboard: 'Focus enters on open and is trapped; Escape closes; focus returns to the trigger.',
    responsive: 'Typed placement; `responsive` is a bottom sheet on mobile and a side panel from tablet up, by CSS only.',
    theme: 'Scrim and raised surface are semantic tokens.',
  },
  {
    name: 'SvPopover',
    category: 'overlay',
    source: `${UI}SvPopover.vue`,
    test: OVERLAYS,
    purpose: 'Anchored, non-modal content. Never hover-only.',
    states: ['expanded'],
    keyboard: 'Escape closes and returns focus to the trigger; outside click closes.',
    responsive: 'Width-capped to the viewport, so it cannot push the page sideways.',
    theme: 'Raised surface and border tokens.',
  },
  {
    name: 'SvMenu',
    category: 'overlay',
    source: `${UI}SvMenu.vue`,
    test: OVERLAYS,
    purpose: 'An ACTION menu implementing the WAI-ARIA menu-button pattern.',
    states: ['disabled', 'expanded'],
    keyboard: 'Down/Up open and cycle, Home/End jump, Escape closes, disabled items are skipped.',
    responsive: 'Width-capped to the viewport.',
    theme: 'Destructive items use error tokens.',
  },
  {
    name: 'SvTabs',
    category: 'overlay',
    source: `${UI}SvTabs.vue`,
    test: OVERLAYS,
    purpose: 'The WAI-ARIA tabs pattern with roving tabindex.',
    states: ['disabled', 'selected'],
    keyboard: 'Arrow keys move focus; activation is automatic or manual by typed prop.',
    responsive: 'The tablist wraps rather than scrolling.',
    theme: 'Active tab uses the brand token.',
  },
  {
    name: 'SvAccordion',
    category: 'overlay',
    source: `${UI}SvAccordion.vue`,
    test: OVERLAYS,
    purpose: 'A disclosure group whose headers are headings containing buttons.',
    states: ['disabled', 'expanded'],
    keyboard: 'Native buttons; aria-expanded and aria-controls are wired both ways.',
    responsive: 'Full width at every breakpoint.',
    theme: 'Border and surface tokens.',
  },
  {
    name: 'SvTooltip',
    category: 'overlay',
    source: `${UI}SvTooltip.vue`,
    test: OVERLAYS,
    purpose: 'Supplementary hint text. Never the only accessible name.',
    states: ['expanded'],
    keyboard: 'Shows on focus, dismissible with Escape without moving focus (WCAG 1.4.13).',
    responsive: 'Width-capped; never contains interactive content.',
    theme: 'Raised surface with a ring token.',
  },

  // ------------------------------------------------------------------ forms
  {
    name: 'SvFormField',
    category: 'form',
    source: `${UI}SvFormField.vue`,
    test: FORMS,
    purpose: 'The single owner of label, help, error and described-by association.',
    states: ['disabled', 'readonly', 'error'],
    keyboard: 'not_applicable — it wraps a control rather than being one.',
    responsive: 'Full width; the message row is always reserved so fields do not jump.',
    theme: 'Four status tones from semantic tokens.',
  },
  {
    name: 'SvTextInput',
    category: 'form',
    source: `${UI}SvTextInput.vue`,
    test: FORMS,
    purpose: 'A single-line text control over a native input.',
    states: ['disabled', 'readonly', 'error'],
    keyboard: 'Native input.',
    responsive: 'Full width with a 44px minimum height.',
    theme: 'Input border and disabled tokens.',
  },
  {
    name: 'SvTextArea',
    category: 'form',
    source: `${UI}SvTextArea.vue`,
    test: FORMS,
    purpose: 'A multi-line text control with a counter that appears only near the limit.',
    states: ['disabled', 'readonly', 'error'],
    keyboard: 'Native textarea.',
    responsive: 'Full width.',
    theme: 'Input border and disabled tokens.',
  },
  {
    name: 'SvSelect',
    category: 'form',
    source: `${UI}SvSelect.vue`,
    test: FORMS,
    purpose: 'A native select with option groups. The default choice over a custom listbox.',
    states: ['disabled', 'error'],
    keyboard: 'Native select — the platform picker on mobile.',
    responsive: 'Full width with a 44px minimum height.',
    theme: 'Input border and disabled tokens.',
  },
  {
    name: 'SvCombobox',
    category: 'form',
    source: `${UI}SvCombobox.vue`,
    test: FORMS,
    purpose: 'A filterable single-select for a long or server-loaded list.',
    states: ['loading', 'disabled', 'error', 'empty', 'expanded', 'selected'],
    keyboard: 'Full combobox pattern with aria-activedescendant; Escape closes and keeps focus.',
    responsive: 'Listbox is height- and width-capped.',
    theme: 'Selected option uses the selected-state tokens.',
  },
  {
    name: 'SvCheckbox',
    category: 'form',
    source: `${UI}SvCheckbox.vue`,
    test: FORMS,
    purpose: 'A native checkbox. Deliberately not a switch.',
    states: ['disabled', 'error', 'selected'],
    keyboard: 'Native checkbox; indeterminate is set as a DOM property.',
    responsive: 'Full width row.',
    theme: 'Brand accent and input border tokens.',
  },
  {
    name: 'SvRadioGroup',
    category: 'form',
    source: `${UI}SvRadioGroup.vue`,
    test: FORMS,
    purpose: 'A single choice in a fieldset with a legend, so the GROUP is named.',
    states: ['disabled', 'error', 'selected'],
    keyboard: 'Native radios — the browser supplies roving arrow-key navigation.',
    responsive: 'Stacks on mobile; optional inline layout from tablet up.',
    theme: 'Brand accent and input border tokens.',
  },
  {
    name: 'SvDatePicker',
    category: 'form',
    source: `${UI}SvDatePicker.vue`,
    test: FORMS,
    purpose: 'A business-date field over the native date input. No date library added.',
    states: ['disabled', 'readonly', 'error'],
    keyboard: 'Native date input — platform keyboard and picker support.',
    responsive: 'Full width; the platform supplies the mobile picker.',
    theme: 'Input border and disabled tokens.',
  },
  {
    name: 'SvMoneyInput',
    category: 'form',
    source: `${UI}SvMoneyInput.vue`,
    test: FORMS,
    purpose: 'An amount field emitting integer minor units. Empty is null, never zero.',
    states: ['disabled', 'readonly', 'error'],
    keyboard: 'Native input with decimal inputmode; tidies to two decimals on blur only.',
    responsive: 'Full width with a currency affix.',
    theme: 'Subtle affix surface and input border tokens.',
  },
  {
    name: 'SvPhoneInput',
    category: 'form',
    source: `${UI}SvPhoneInput.vue`,
    test: FORMS,
    purpose: 'A phone field that previews the canonical form without rewriting the entry.',
    states: ['disabled', 'readonly', 'error'],
    keyboard: 'Native tel input.',
    responsive: 'Full width.',
    theme: 'Muted preview line uses a semantic token.',
  },
  {
    name: 'SvFileUpload',
    category: 'form',
    source: 'resources/spa/src/components/files/SvFileUpload.vue',
    test: 'resources/spa/src/components/files/SvFileUpload.spec.ts',
    purpose: 'The Phase 10F file-selection foundation. No direct provider integration.',
    states: ['loading', 'disabled', 'error'],
    keyboard: 'Native file input with a labelled trigger.',
    responsive: 'Full width.',
    theme: 'Status text uses semantic status tokens.',
  },
  {
    name: 'SvSearchInput',
    category: 'form',
    source: `${UI}SvSearchInput.vue`,
    test: FORMS,
    purpose: 'A native search field with a named clear control. Issues no requests.',
    states: ['disabled'],
    keyboard: 'Native search input; clearing returns focus to the field.',
    responsive: 'Full width.',
    theme: 'Input border and muted icon tokens.',
  },
  {
    name: 'SvFilterBar',
    category: 'form',
    source: `${UI}SvFilterBar.vue`,
    test: FORMS,
    purpose: 'The filter region above a list. Holds no business or query knowledge.',
    states: ['expanded'],
    keyboard: 'The mobile disclosure is a native button with aria-expanded.',
    responsive: 'Collapses behind a disclosure on mobile; always visible from tablet up.',
    theme: 'Brand count badge and input border tokens.',
  },

  // ------------------------------------------------------------------ data
  {
    name: 'SvDataTable',
    category: 'data',
    source: `${UI}SvDataTable.vue`,
    test: DATA,
    purpose: 'The desktop/tablet semantic table, driven by the shared column contract.',
    states: ['loading', 'error', 'empty'],
    keyboard: 'Sort headers are native buttons; an opt-in scroll region is keyboard scrollable.',
    responsive: 'Renders from tablet up; SvResponsiveRecordList renders on mobile.',
    theme: 'Header, row hover and border tokens.',
  },
  {
    name: 'SvResponsiveRecordList',
    category: 'data',
    source: `${UI}SvResponsiveRecordList.vue`,
    test: DATA,
    purpose: 'The mobile labelled record cards, from the SAME column contract. Loses nothing.',
    states: ['loading', 'error', 'empty', 'expanded'],
    keyboard: 'The per-card detail disclosure is a native button with aria-expanded.',
    responsive: 'The mobile counterpart of SvDataTable; never scrolls horizontally.',
    theme: 'Raised surface and border tokens.',
  },
  {
    name: 'SvPagination',
    category: 'data',
    source: `${UI}SvPagination.vue`,
    test: DATA,
    purpose: 'Page navigation reporting only what the server supplied.',
    states: ['disabled'],
    keyboard: 'Named previous/next icon buttons, disabled at the boundaries.',
    responsive: 'Compact label on mobile, spelled out from tablet up.',
    theme: 'Subtle control tokens.',
  },
  {
    name: 'SvTimeline',
    category: 'data',
    source: `${UI}SvTimeline.vue`,
    test: DATA,
    purpose: 'An ordered event sequence that implies no causality beyond the source data.',
    states: [],
    keyboard: 'not_applicable — presentation only.',
    responsive: 'Single column at every breakpoint.',
    theme: 'Brand marker and border tokens; status carried by SvStatusBadge.',
  },
  {
    name: 'SvAuditEvent',
    category: 'data',
    source: `${UI}SvAuditEvent.vue`,
    test: DATA,
    purpose: 'One audit row. Read-only by construction; masking stays server-side.',
    states: ['expanded'],
    keyboard: 'The metadata disclosure is a native details/summary.',
    responsive: 'Single column at every breakpoint.',
    theme: 'Raised surface and muted label tokens.',
  },

  // ------------------------------------------------------------------ shell
  {
    name: 'SvProfileControl',
    category: 'shell',
    source: `${UI}SvProfileControl.vue`,
    test: SHELL,
    purpose: 'The identity unit in the shell header, hosting the account switch and logout.',
    states: ['expanded'],
    keyboard: 'Opens on click, Escape closes, focus returns to the trigger.',
    responsive: 'Avatar-only on mobile with a full screen-reader name; text from tablet up.',
    theme: 'Warm avatar surface and raised menu tokens.',
  },
  {
    name: 'SvAccountContextSwitcher',
    category: 'shell',
    source: `${UI}SvAccountContextSwitcher.vue`,
    test: SHELL,
    purpose: 'The final presentation of UI-03’s account switch. Holds no security logic.',
    states: ['loading', 'disabled', 'error', 'expanded', 'selected'],
    keyboard: 'Native buttons; Escape closes and returns focus to the trigger.',
    responsive: 'Menu or inline variant; width-capped to the viewport.',
    theme: 'Selected-state tokens mark the current context.',
  },
  {
    name: 'SvNotificationsControl',
    category: 'shell',
    source: `${UI}SvNotificationsControl.vue`,
    test: SHELL,
    purpose: 'The notifications visual contract. Data-driven; no notification API exists yet.',
    states: ['loading', 'error', 'empty', 'expanded'],
    keyboard: 'Named icon-button trigger; Escape closes and returns focus.',
    responsive: 'Panel is height- and width-capped.',
    theme: 'Error badge and raised panel tokens.',
  },
  {
    name: 'SvThemeToggle',
    category: 'shell',
    source: `${UI}SvThemeToggle.vue`,
    test: SHELL,
    purpose: 'The one theme control. Writes to the user record when signed in.',
    states: ['loading', 'selected'],
    keyboard: 'Native button/switch with an accessible name describing the action.',
    responsive: 'Icon variant in the footer; labelled switch variant in preferences.',
    theme: 'It IS the theme control; both variants are token-backed.',
  },
  {
    name: 'SvFixedFooter',
    category: 'shell',
    source: `${UI}SvFixedFooter.vue`,
    test: SHELL,
    purpose: 'The viewport-fixed footer whose height token also drives the page reserve.',
    states: [],
    keyboard: 'All links are native anchors, last in the document order.',
    responsive: 'Three height tokens plus a zoom fallback; stacks on mobile.',
    theme: 'Footer surface, text and border tokens, contrast-checked in both themes.',
  },

  // ------------------------------------------------------------------ content
  {
    name: 'SvLandingSection',
    category: 'content',
    source: `${UI}SvLandingSection.vue`,
    test: CONTENT,
    purpose: 'A landing section shell named by its own heading. Contains no copy.',
    states: [],
    keyboard: 'not_applicable — a layout region.',
    responsive: 'Stacks on mobile; content and media sit side by side from desktop.',
    theme: 'Three surface tones from semantic tokens.',
  },
  {
    name: 'SvLegalDocument',
    category: 'content',
    source: `${UI}SvLegalDocument.vue`,
    test: CONTENT,
    purpose: 'Renders an approved legal document verbatim through the escaping markdown renderer.',
    states: [],
    keyboard: 'not_applicable — a document.',
    responsive: 'Constrained to a readable measure.',
    theme: 'Prose colours from semantic tokens.',
  },
  {
    name: 'SvFaq',
    category: 'content',
    source: `${UI}SvFaq.vue`,
    test: CONTENT,
    purpose: 'An accessible FAQ disclosure over native details/summary. Fabricates nothing.',
    states: ['expanded'],
    keyboard: 'Native details/summary — keyboard and state support from the platform.',
    responsive: 'Full width at every breakpoint.',
    theme: 'Raised surface and border tokens.',
  },
]);

/** Every component name, for a quick membership check. */
export const COMPONENT_NAMES: readonly string[] = Object.freeze(
  COMPONENT_REGISTRY.map((entry) => entry.name),
);
