<?php

declare(strict_types=1);

namespace App\Domain\Payments\Actions;

use App\Domain\Audit\Contracts\AuditRecorder;
use App\Domain\Audit\Enums\AuditEvent;
use App\Domain\Compensation\Services\CommissionHandoffWriter;
use App\Domain\FinanceOps\Services\FinancialPeriodGuard;
use App\Domain\Invoicing\Enums\InvoiceStatus;
use App\Domain\Invoicing\Models\Invoice;
use App\Domain\Invoicing\Services\InvoiceStateMachine;
use App\Domain\Payments\Enums\PaymentRecordingGroupStatus;
use App\Domain\Payments\Enums\PaymentRecordStatus;
use App\Domain\Payments\Enums\PaymentValidationDecision;
use App\Domain\Payments\Exceptions\PaymentValidationException;
use App\Domain\Payments\Models\PaymentRecord;
use App\Domain\Payments\Models\PaymentRecordingGroup;
use App\Domain\Payments\Models\PaymentValidationEvent;
use App\Domain\Payments\Services\PaymentMakerCheckerGuard;
use App\Domain\Payments\Services\PaymentRecordingGroupStateMachine;
use App\Domain\Receipts\Jobs\GenerateReceiptPdf;
use App\Domain\Receipts\Models\Receipt;
use App\Domain\Receipts\Services\ReceiptIssuer;
use App\Models\User;
use Carbon\CarbonImmutable;
use Illuminate\Support\Facades\DB;

/**
 * Validate a WHOLE pending payment recording group as the Finance checker (Plan §42;
 * Gate A/B/C/J; Phase 18B). One atomic transaction performs the full sequence:
 * period-lock gate → lock the group, invoice and every component → maker/checker →
 * revalidate total/currency/sum → one immutable group validation event → mark every
 * component validated → group validated → increase invoice validated_paid_minor +
 * derive the payment state → one gap-free original receipt (durable, PDF pending) →
 * durable per-component 20G commission handoff → safe audit. Any failure rolls back
 * EVERYTHING (no event, no receipt, no number consumed, no handoff, no success audit).
 * The invoice can never appear paid without a durable receipt + handoff. The receipt
 * PDF is generated by an outbox job dispatched AFTER commit.
 *
 * There is no partial group validation: components move to the group decision or the
 * transaction rolls back (Gate B).
 */
final class ValidatePaymentRecordingGroup
{
    public function __construct(
        private readonly FinancialPeriodGuard $periodGuard,
        private readonly PaymentMakerCheckerGuard $makerChecker,
        private readonly PaymentRecordingGroupStateMachine $machine,
        private readonly InvoiceStateMachine $invoiceMachine,
        private readonly ReceiptIssuer $receipts,
        private readonly CommissionHandoffWriter $commission,
        private readonly AuditRecorder $audit,
    ) {}

    public function handle(PaymentRecordingGroup $group, User $checker): PaymentValidationEvent
    {
        // Period openness before the write (→ 423 financial_period_locked).
        $this->periodGuard->ensureOpen($group->merchant_id, $group->branch_id);

        $event = DB::transaction(function () use ($group, $checker): PaymentValidationEvent {
            /** @var PaymentRecordingGroup $lockedGroup */
            $lockedGroup = PaymentRecordingGroup::query()->whereKey($group->id)->lockForUpdate()->firstOrFail();

            // Maker/checker: the recording maker may never validate their own group.
            $this->makerChecker->ensureNotMaker($lockedGroup, $checker->id);

            // Source state must be pending_validation (else 422 invalid_state_transition).
            $this->machine->ensure($lockedGroup->status, PaymentRecordingGroupStatus::Validated);

            /** @var Invoice $invoice */
            $invoice = Invoice::query()->whereKey($lockedGroup->invoice_id)->lockForUpdate()->firstOrFail();

            /** @var list<PaymentRecord> $components */
            $components = PaymentRecord::query()
                ->where('payment_recording_group_id', $lockedGroup->id)
                ->lockForUpdate()
                ->get()
                ->all();

            // Revalidate group total = Σ components, single currency.
            $sum = 0;
            foreach ($components as $component) {
                if ($component->currency !== $lockedGroup->currency) {
                    throw PaymentValidationException::componentSumMismatch();
                }
                $sum += $component->amount_minor;
            }
            if ($sum !== $lockedGroup->total_amount_minor || $components === []) {
                throw PaymentValidationException::componentSumMismatch();
            }

            $recognised = $lockedGroup->total_amount_minor;
            if ($recognised <= 0) {
                throw PaymentValidationException::nothingToValidate();
            }

            // Invoice recognised-paid must stay within 0..total (else roll back).
            $newValidatedPaid = $invoice->validated_paid_minor + $recognised;
            if ($newValidatedPaid > $invoice->total_minor) {
                throw PaymentValidationException::validatedPaidOverflow();
            }

            $now = CarbonImmutable::now();

            // 1) Immutable group validation event.
            $event = PaymentValidationEvent::create([
                'merchant_id' => $lockedGroup->merchant_id,
                'branch_id' => $lockedGroup->branch_id,
                'payment_recording_group_id' => $lockedGroup->id,
                'invoice_id' => $invoice->id,
                'checker_user_id' => $checker->id,
                'decision' => PaymentValidationDecision::Validated,
                'validated_amount_minor' => $recognised,
                'reason' => null,
            ]);

            // 2) Every component validated (coherent with the group; no partial validation).
            foreach ($components as $component) {
                $component->forceFill([
                    'status' => PaymentRecordStatus::Validated->value,
                    'validated_amount_minor' => $component->amount_minor,
                ])->save();
            }

            // 3) Group validated.
            $lockedGroup->forceFill([
                'status' => PaymentRecordingGroupStatus::Validated->value,
                'validated_at' => $now,
            ])->save();

            // 4) Invoice recognised balance + derived payment state.
            $target = $newValidatedPaid === $invoice->total_minor
                ? InvoiceStatus::Paid
                : InvoiceStatus::PartiallyPaid;
            if ($invoice->status !== $target) {
                $this->invoiceMachine->ensure($invoice->status, $target);
                $invoice->status = $target;
            }
            $invoice->validated_paid_minor = $newValidatedPaid;
            $invoice->save();

            // 5) One gap-free original receipt (durable; PDF generated after commit).
            $receipt = $this->receipts->issueOriginal($invoice, $event, $components);

            // 6) Durable per-component 20G commission handoff (no invented rate).
            foreach ($components as $component) {
                $this->commission->recordValidatedAllocation($event, $component, $now);
            }

            // 7) Safe audit — masked/ULID/integer only.
            $context = $this->context($lockedGroup, $invoice, $receipt, $components);
            $this->audit->record(AuditEvent::CustomerPaymentValidated, $checker, $lockedGroup->merchant_id, $lockedGroup->branch_id, $lockedGroup, $context);
            $this->audit->record(AuditEvent::ReceiptIssued, $checker, $lockedGroup->merchant_id, $lockedGroup->branch_id, $receipt, [
                'receipt_id' => $receipt->ulid,
                'receipt_number' => $receipt->receipt_number,
                'invoice_id' => $invoice->ulid,
                'amount_minor' => $receipt->amount_minor,
                'currency' => $receipt->currency,
            ]);

            // Outbox: generate the receipt PDF only after the financial txn commits.
            GenerateReceiptPdf::dispatch($receipt->id, $lockedGroup->merchant_id, $lockedGroup->branch_id)
                ->afterCommit()
                ->onQueue((string) config('files.queue', 'default'));

            return $event->setRelation('group', $lockedGroup)->setRelation('invoice', $invoice);
        });

        return $event;
    }

    /**
     * @param  list<PaymentRecord>  $components
     * @return array<string, mixed>
     */
    private function context(PaymentRecordingGroup $group, Invoice $invoice, Receipt $receipt, array $components): array
    {
        return [
            'group_id' => $group->ulid,
            'invoice_id' => $invoice->ulid,
            'invoice_number' => $invoice->invoice_number,
            'component_count' => count($components),
            'component_methods' => array_map(static fn (PaymentRecord $c): string => $c->method->value, $components),
            'validated_amount_minor' => $group->total_amount_minor,
            'currency' => $group->currency,
            'invoice_validated_paid_minor' => $invoice->validated_paid_minor,
            'invoice_total_minor' => $invoice->total_minor,
            'invoice_state' => $invoice->status->value,
            'receipt_id' => $receipt->ulid,
            'receipt_number' => $receipt->receipt_number,
        ];
    }
}
