import type { LegalDocType } from '@/content/roleContent';
import type { RoleIdentity } from '@/types/roles';
import { loadGeneratedLegal } from '@/content/generated/index.generated';
import type { GeneratedLegalDocument } from '@/content/generated/contentTypes.generated';

/**
 * Lazily-loaded legal documents.
 *
 * Phase 11 loaded these with `import.meta.glob('../../../../docs/legal/**\/*.md', '?raw')`, which
 * reached out of the SPA source tree at build time and resolved whatever happened to be on disk.
 * Phase UI-05 replaced that with generated, source-controlled modules (UI/UX plan §8.8): the
 * approved text still lives once, verbatim, in `docs/legal/**`, and is still never hand-copied —
 * `scripts/generate-role-content.mjs` copies it byte for byte into one typed module per role and
 * document, records the source hash, and CI fails when the generated bytes drift from the source.
 *
 * Loading stays one document at a time. Each generated module is its own static dynamic import, so
 * Vite emits a separate chunk and viewing one legal page fetches only that document rather than
 * every role's ~3 MB of legal text.
 */

/** `terms-of-service` (route/UI vocabulary) → `terms_of_service` (content-category vocabulary). */
const CATEGORY_BY_DOC_TYPE = {
  'terms-of-service': 'terms_of_service',
  'privacy-policy': 'privacy_policy',
  'data-policy': 'data_policy',
} as const;

/**
 * Resolve a role's legal document.
 *
 * Fails closed: an unknown role or document type throws rather than falling back to another role's
 * document, which is the cross-role leak UI/UX plan §17.1 forbids.
 */
export async function loadLegalDocument(
  identity: RoleIdentity,
  type: LegalDocType,
): Promise<GeneratedLegalDocument> {
  const category = CATEGORY_BY_DOC_TYPE[type];
  if (category === undefined) {
    throw new Error(`Legal document not found: ${identity}/${type}`);
  }
  return loadGeneratedLegal(identity, category);
}

/** The verbatim markdown for a role's legal document. */
export async function loadLegalDoc(identity: RoleIdentity, type: LegalDocType): Promise<string> {
  return (await loadLegalDocument(identity, type)).markdown;
}
