import { existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import inventoryJson from '@docs/frontend/screens/inventory.json';
import { router } from '@/router';

/**
 * Screen-inventory coverage guard (Plan §27.1, §27.3; REM-SCR-001). The JSON is
 * the source of truth; the YAML is generated from it and specs are generated by
 * scripts/generate-screen-specs.mjs. This guard fails when an implemented route
 * lacks a spec, an inventory status conflicts with the router, a planned screen
 * invents a route, an entry lacks an owning phase, or keys/routes duplicate.
 */
interface Screen {
  key: string;
  domain: string;
  route: string | null;
  layout: string;
  status: 'implemented' | 'phase_11' | 'planned';
  phase: string;
  spec: string | null;
  title: string;
}

const screens = (inventoryJson as { screens: Screen[] }).screens;
const SCREENS_DIR = resolve(import.meta.dirname, '../../../../docs/frontend/screens');

function routerNames(): Set<string> {
  return new Set(
    router
      .getRoutes()
      .map((r) => r.name)
      .filter((n): n is string => typeof n === 'string'),
  );
}

describe('screen inventory coverage', () => {
  it('has no duplicate screen keys', () => {
    const keys = screens.map((s) => s.key);
    expect(new Set(keys).size).toBe(keys.length);
  });

  it('has no duplicate route names', () => {
    const routes = screens.map((s) => s.route).filter((r): r is string => r !== null);
    expect(new Set(routes).size).toBe(routes.length);
  });

  it('every entry declares an owning phase', () => {
    for (const s of screens) expect(s.phase, s.key).toBeTruthy();
  });

  it('implemented and phase_11 routed screens map to a registered route', () => {
    const names = routerNames();
    for (const s of screens) {
      if ((s.status === 'implemented' || s.status === 'phase_11') && s.route) {
        expect(names.has(s.route), `${s.key} → ${s.route}`).toBe(true);
      }
    }
  });

  it('planned screens never invent a route (no fake/dead routes)', () => {
    const names = routerNames();
    for (const s of screens) {
      if (s.status === 'planned') {
        expect(s.route, `${s.key} planned route`).toBeNull();
        // And no router route may secretly exist for a planned key.
        expect(names.has(s.key)).toBe(false);
      }
    }
  });

  it('implemented + phase_11 screens have a spec file that exists on disk', () => {
    for (const s of screens) {
      if (s.status === 'implemented' || s.status === 'phase_11') {
        expect(s.spec, `${s.key} spec path`).toBeTruthy();
        expect(existsSync(resolve(SCREENS_DIR, s.spec as string)), `${s.spec} exists`).toBe(true);
      }
    }
  });

  it('every implemented production route is covered by the inventory', () => {
    const covered = new Set(
      screens
        .filter((s) => s.status === 'implemented' || s.status === 'phase_11')
        .map((s) => s.route)
        .filter((r): r is string => r !== null),
    );
    for (const name of routerNames()) {
      expect(covered.has(name), `route ${name} has an inventory entry`).toBe(true);
    }
  });

  it('matches the generated inventory.yaml fixture', async () => {
    const lines: string[] = [
      '# Servana screen inventory (Plan §27.3). Generated from inventory.json.',
      '# Enforced by screenInventory.spec.ts (vitest file snapshot). Do not hand-edit.',
      'screens:',
    ];
    for (const s of screens) {
      lines.push(`  - key: ${s.key}`);
      lines.push(`    domain: ${s.domain}`);
      lines.push(`    route: ${s.route ?? '~'}`);
      lines.push(`    status: ${s.status}`);
      lines.push(`    phase: ${s.phase}`);
      lines.push(`    spec: ${s.spec ?? '~'}`);
    }
    await expect(`${lines.join('\n')}\n`).toMatchFileSnapshot(
      resolve(SCREENS_DIR, 'inventory.yaml'),
    );
  });
});
